#!/usr/bin/Rscript

if(!require(shiny)){install.packages("shiny")}
if(!require(npsm)){install.packages("npsm")}
if(!require(Rfit)){install.packages("Rfit")}

library(shiny)
library(npsm)
library(Rfit)

dir = "src"
port = 12345

runApp(appDir = dir, port = port)
